Udpate fn run doc
GoogleContainerTools/kpt pull request #1023
Opened 2020-09-11 22:11 UTC by Shell32-Natsu

Add a section for using imperative and declarative functions at the same time.

2020-09-11 22:18 UTC, frankfarzan commented on site/content/en/reference/fn/run/_index.md
> +#### Use Imperative and Declarative at the same time
Title is misleading because this is not allowed

2020-09-12 00:49 UTC, mortent commented
Use the `docs:` prefix on the commit message(s) so we can filter out this from the release notes.

2020-09-16 18:09 UTC, prachirp requested changes

2020-09-25 22:53 UTC, prachirp approved these changes
LGTM. Can you move Scoping Rules section above Imperative Run Specifics?

2020-10-12 22:07 UTC, Shell32-Natsu commented
@mortent @frankfarzan Please review.

2020-11-06 20:50 UTC, frankfarzan approved these changes

2020-11-06 20:51 UTC, merged