Use Pkg type for Get and Fetch commands
GoogleContainerTools/kpt pull request #1583
Opened 2021-03-19 21:49 UTC by mortent

Updates the `Get` and `Fetch` functionality to use the `pkg.Pkg` structure. 

As part of this, it also makes some changes to the `pkg.Pkg` functionality:
 * The `pkg.Kptfile()` function returns an error if a `Kptfile` doesn't exist instead of returning an empty Kptfile. We no longer have the concept of implicit packages.
 * Updates the `pkg.Subpackages` function to include all subpackages, and not only subpackages in the direct subfolders. Also adds tests for this function.

Must merge after https://github.com/GoogleContainerTools/kpt/pull/1568

2021-03-22 19:07 UTC, frankfarzan requested changes

2021-03-22 19:07 UTC, frankfarzan commented on internal/pkg/pkg.go
> +		for dir := range packagePaths {
Can't you skip walking subpackages using filepath.SkipDir?

You should avoid doing path computations in favor of using just `info`

2021-03-22 19:07 UTC, frankfarzan commented on internal/pkg/pkg.go
> +	if err := filepath.Walk(pkgPath, func(path string, info os.FileInfo, err error) error {
Walk does not follow symlinks.

2021-03-23 00:52 UTC, mortent commented on internal/pkg/pkg.go
> +		// Ignore anything inside the .git folder
Yeah, we have an issue for this. We just haven't gotten to it yet.

2021-03-23 00:53 UTC, mortent commented on internal/pkg/pkg.go
> +func (p *Pkg) SubPackages() ([]*Pkg, error) {
Renamed the function to `DirectSubpackages` for now. Not yet sure if we need to list all recursive packages. I will see when I try to phase out the `pkgutil` package if we need more.

2021-03-23 00:53 UTC, mortent commented on internal/pkg/pkg.go
> +	if err := filepath.Walk(pkgPath, func(path string, info os.FileInfo, err error) error {
Added a TODO.

2021-03-23 22:03 UTC, frankfarzan reviewed
lgtm for Package (I glossed over other files) with minor comments.

2021-03-23 22:03 UTC, frankfarzan commented on internal/pkg/pkg.go
> +		if info.Name() == ".git" && info.IsDir() {
nit move this inside the next if statement
```
if info.isDir() {
  if info.Name() == ".git" {}
  if isPackageDir(..) {}
 }
```

2021-03-23 22:03 UTC, frankfarzan commented on internal/pkg/pkg.go
> +			kfPath := filepath.Join(path, kptfilev1alpha2.KptFileName)
Extract a function isPackageDir() for this

2021-03-23 22:04 UTC, frankfarzan commented on internal/pkg/pkg.go
> +		// Ignore anything inside the .git folder
Add a TODO with the issue?

2021-03-24 00:03 UTC, frankfarzan approved these changes

2021-03-24 00:05 UTC, merged