Improve update
GoogleContainerTools/kpt pull request #1590
Opened 2021-03-22 16:58 UTC by mortent

This updates the packaging functionality to handle deletion of packages in upstream. During update, a package that is deleted in upstream will also be deleted in the local fork. The only current exception is if the upstream information in the package Kptfile has changed. Eventually we should do a full diff with all resources to determine if there are local changes, but this would also need to be aware of hydration. We have an issue to address this: https://github.com/GoogleContainerTools/kpt/issues/1438

2021-03-22 20:03 UTC, phanimarupaka requested changes

2021-03-23 03:14 UTC, mortent commented on internal/util/update/common.go
> +func PkgHasLocalChanges(local, origin string) (bool, error) {
Good point. I have updated the name of the function and added a comment.

2021-03-23 03:16 UTC, mortent commented on internal/util/update/resource-merge_test.go
> +						WithUpstream("github.com/GoogleContainerTools/kpt", "/", "v1.0", "resource-merge"),
That is not a problem. That just means a remote subpackage has been published together with the parent package. I have updated the testcases here to be a bit more realistic. In particular, when merging a subpackage that is not the root, but does have an upstream, we would expect it to be either empty ("unfetched", which kpt doesn't fully handle yet) and not have an `UpstreamLock`, or have the the package content as well as the `UpstreamLock` information.

2021-03-23 03:20 UTC, mortent commented on internal/util/update/resource-merge_test.go
> +						WithUpstreamLock("github.com/GoogleContainerTools/kpt", "/", "master", "abc123"),
In this case no. For packages that are the root of the current hierarchy that is being merged, updating the Kptfile is done by code outside of each merge strategy.

2021-03-24 17:48 UTC, phanimarupaka approved these changes

2021-03-24 18:21 UTC, merged